export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const UPDATE_TODOS = 'UPDATE_TODOS' 
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_USER = 'SET_USER'
export const TOGGLE_LOGIN_VIEW = 'TOGGLE_LOGIN_VIEW'
export const SET_LOGIN_ERRORMESSAGE = 'SET_LOGIN_ERRORMESSAGE'
